=== aptomar/apt-file-format/src/apt.schema.json
{
      "type":"object",
      "$schema": "http://json-schema.org/draft-04/schema",
      "id": "https://aptomar.com/pub/dev/apt.schema.json",
      "minProperties": 4,
      "maxProperties": 5,
      "definitions": {
        "dataset": {
          "type":"array",
          "title": "A set of files",
          "description": "Files in the archive that contain the data of interest",
          "minitems": "1",
          "items":{
            "type":"string",
            "title":"Data-URI encoded reference.",
            "description": "Use 'data:<mime-type>[;base64],<...>' for data URIs, 'file:<...>' for file references, and 'http://<host>/<file>' for external references."
          }
        },
        "date": {
          "type":"string",
          "title": "Datestamp",
          "description": "ISO 8601 date.",
          "format": "date-time"
        },
        "description": {
          "type":"string",
          "title": "Description",
          "description": "The detailed description of the data element"
        },
        "name": {
          "type":"string",
          "title": "Content name",
          "description": "The display name of the data element"
        },
        "georeference": {
          "type":"object",
          "title": "Georeference",
          "description": "A georeference object that locates the element in space.",
          "properties":{
            "elevation": {
              "type":"number",
              "title": "Georeference elevation",
              "description": "The elevation of the object."
            },
            "latitude": {
              "type":"number",
              "title": "Georeference latitude",
              "description": "The latitude of the object."
            },
            "longitude": {
              "type":"number",
              "title": "Georeference longitude",
              "description": "The longitude of the object."
            }
          },
          "required": ["elevation","latitude","longitude"]
        },
        "geometry": {
          "type":"object",
          "title": "Data geometry",
          "description": "The geometry of the data element",
          "properties":{
            "data": {
              "$ref": "#/definitions/dataset"     
            },
            "type": {
              "type":"string",
              "title": "Geometry type",
              "description": "The pseudo-mime type of the geometry.  E.g. 'text/x-ewkt'.  The type controls the interpretation of the 'data' elements.",
              "enum": ["text/x-ewkt"]
            }
          },
          "required": ["data","type"]
        }
      },
      "required": ["date","description","manifest_version","generator"],
      "additionalProperties": false,
      "properties":{
        "area": {
          "type":"object",
          "additionalProperties": false,
          "properties":{
            "created": {
              "$ref": "#/definitions/date"
            },
            "description": {
              "$ref": "#/definitions/description"
            },
            "name": {
              "$ref": "#/definitions/name"
            },
            "geometry": {
              "$ref": "#/definitions/geometry"
            }
          },
          "required": ["created","description","name","geometry"]
        },
        "asset": {
          "type":"object",
          "additionalProperties": false,
          "required": ["groups", "layers"],
          "properties":{
            "groups": {
              "type":"object",
              "minProperties": 1,
              "additionalProperties": false,
              "patternProperties":{
                "group": {
                  "type":"object",
                  "additionalProperties": false,
                  "properties":{
                    "layers": {
                      "type":"array",
                      "title": "Group layers",
                      "description": "This is an array of layers that are included in the group.",
                      "minitems": "1",
                      "items":{
                        "type":"string"
                      }
                    },
                    "name": {
                      "type":"string",
                      "title": "Group name",
                      "description": "The name of the group.  Required for display purposes."
                    }
                  },
                  "required": ["layers", "name"]
                }
              }
            },
            "layers": {
              "type":"object",
              "title": "Data layers",
              "description": "The data layers included in the .apt archive.",
              "minProperties": 1,
              "additionalProperties": false,
              "patternProperties":{
                "layer": {
                  "type":"object",
                  "required": ["geometry","name","style"],
                  "additionalProperties": false,
                  "properties":{
                    "geometry": {
                      "type":"object",
                      "additionalProperties": false,
                      "properties":{
                        "data": {
                          "$ref": "#/definitions/dataset"
                        },
                        "type": {
                          "type":"string",
                          "enum": ["text/x-shapefile"]
                        }
                      },
                      "required": ["data", "type"]
                    },
                    "name": {
                      "type":"string",
                      "title": "Layer name",
                      "description": "The name of the layer.  Required for display purposes."
                    },
                    "resources": {
                      "type":"object",
                      "title": "Layer resources",
                      "description": "The resources needed for styling the layer",
                      "additionalProperties": false,
                      "properties":{
                        "data": {
                          "$ref": "#/definitions/dataset"
                        }
                      },
                      "required": ["data"]
                    },
                    "style": {
                      "type":"object",
                      "title": "Layer style",
                      "description": "The style description for the layer",
                      "additionalProperties": false,
                      "properties":{
                        "data": {
                          "$ref": "#/definitions/dataset"
                        },
                        "type": {
                          "type":"string",
                          "title": "Style type",
                          "description": "The pseudo-mime type of the styling information.  E.g. 'text/x-sld'",
                          "enum": ["text/x-sld"]
                        }
                      },
                      "required": ["data", "type"]
                    }
                  }
                }
              }
            }
          }
        },
        "date": {
          "$ref": "#/definitions/date"
        },
        "description": {
          "$ref": "#/definitions/description"
        },
        "generator": {
          "type":"object",
          "title": "Archive generator",
          "description": "Contains information about the generating program / organization.",
          "required": ["creator","program"],
          "additionalProperties": false,
          "properties":{
            "creator": {
              "type":"string"
            },
            "program": {
              "type":"string"
            }
          }
        },
        "image": {
          "type":"object",
          "required": ["created","description","name","data"],
          "additionalProperties": false,
          "properties":{
            "bounds": {
              "type":"object",
              "title": "Image bounds",
              "description": "The bounds for the image data in the archive",
              "required":["data","type"],
              "additionalProperties": false,
              "properties":{
                "data": {
                  "$ref": "#/definitions/dataset"
                },
                "type": {
                  "type":"string",
                  "title": "Bounds type",
                  "description": "The type of the bounds data.  E.g. 'text/x-worldfile'.",
                  "enum": ["text/x-worldfile"]
                }
              }
            },
            "created": {
              "$ref": "#/definitions/date"
            },
            "description": {
              "$ref": "#/definitions/description"
            },
            "name": {
              "$ref": "#/definitions/name"
            },
            "data": { 
              "$ref": "#/definitions/dataset"         
            },
            "georeference": {
              "$ref": "#/definitions/georeference"
            }
          }
        },
        "manifest_version": {
          "type":"number",
          "title": "Manifest version",
          "description": "The version of the manifest schema used to validate the manifest contents."
        },
        "point": {
          "type":"object",
          "title": "Point-of-Interest",
          "description": "A representation of a point-of-interest",
          "required":["created","description","name","geometry","object-type"],
          "additionalProperties": false,
          "properties":{
            "created": {
              "$ref": "#/definitions/date"
            },
            "description": {
              "$ref": "#/definitions/description"
            },
            "name": {
              "$ref": "#/definitions/name"
            },
            "geometry": {
              "$ref": "#/definitions/geometry"
            },
            "object-type": {
              "type":"string",
              "title": "Object type",
              "description": "The type of the point-of-interest",
              "enum": ["boat", "bouy", "debris", "fishfarm", "green", "oil", "personnel", "red", "unknown", "vessel", "yellow"]
            }
          }
        },
        "route": {
          "type":"object",
          "title": "Route",
          "description": "A represtentation of a route generated by or for display in Scope.",
          "required":["created","description","name","geometry"],
          "additionalProperties": false,
          "properties":{
            "created": {
              "$ref": "#/definitions/date"
            },
            "description": {
              "$ref": "#/definitions/description"
            },
            "name": {
              "$ref": "#/definitions/name"
            },
            "geometry": {
              "$ref": "#/definitions/geometry"
            }
          }
        },
        "video": {
          "type":"object",
          "required":["created","description","name","data"],
          "additionalProperties": false,
          "properties":{
            "created": {
              "$ref": "#/definitions/date"
            },
            "description": {
              "$ref": "#/definitions/description"
            },
            "name": {
              "$ref": "#/definitions/name"
            },
            "data": {
              "$ref": "#/definitions/dataset"
            },
            "georeference": {
              "$ref": "#/definitions/georeference"
            }
          }
        }
      }
    }

=== aptomar/apt-file-format/extras/tests/valid/area.json
{
    "date": "2012-12-19T08:46Z",
    "description": "Text description of the contents for presentation in a confirmation dialog.",
    "generator": { 
        "program": "SuperCool.app",
        "creator": "Aptomar AS"
    },
    "manifest_version": 1,
    
    "area": {
        "name": "The area name",
        "description": "A detailed description of the area",
        "created": "2012–12–19T08:46Z",
        "geometry": {
            "type": "text/x-ewkt",
            "data": ["file:...", "data:...", "http://"]
        }
    }
}

=== aptomar/apt-file-format/extras/tests/valid/image.json
{
    "date": "2012-12-19T08:46Z",
    "description": "Text description of the contents for presentation in a confirmation dialog.",
    "generator": { 
        "program": "SuperCool.app",
        "creator": "Aptomar AS"
    },
    "manifest_version": 1,
    "image": { 
        "name": "The image name",
        "description": "A detailed description of the image",
        "created": "2012–12–19T08:46Z",
        "data": ["file:image.jpg"],
        "georeference": {
            "longitude": 10.4344,
            "latitude": 63.4181,
            "elevation": 150.60
        },
        "bounds": {
            "type": "text/x-worldfile",
            "data": ["data:,bounds as a string, interpreted by type"]
        }
    }
}

=== aptomar/apt-file-format/extras/tests/valid/point.json
{
    "date": "2012-12-19T08:46Z",
    "description": "Text description of the contents for presentation in a confirmation dialog.",
    "generator": { 
        "program": "SuperCool.app",
        "creator": "Aptomar AS"
    },
    "manifest_version": 1,
    "point": {
        "name": "The point name",
        "description": "A detailed description of the point",
        "created": "2012–12–19T08:46Z",
        "object-type": "boat",
        "geometry": {
            "type": "text/x-ewkt",
            "data": ["file:...", "data:...", "http://"]
        }
    }
}

=== aptomar/apt-file-format/extras/tests/valid/video.json
{
    "date": "2012-12-19T08:46Z",
    "description": "Text description of the contents for presentation in a confirmation dialog.",
    "generator": { 
        "program": "SuperCool.app",
        "creator": "Aptomar AS"
    },
    "manifest_version": 1,
    "video": {
        "name": "The video name",
        "description": "A detailed description of the video",
        "created": "2012–12–19T08:46Z",
        "georeference": {
            "longitude": 10.4344,
            "latitude": 63.4181,
            "elevation": 150.60
        },
        "data": ["file:...", "data:...", "http://"]
    }
}

=== aptomar/apt-file-format/extras/tests/valid/route.json
{
    "date": "2012-12-19T08:46Z",
    "description": "Text description of the contents for presentation in a confirmation dialog.",
    "generator": { 
        "program": "SuperCool.app",
        "creator": "Aptomar AS"
    },
    "manifest_version": 1,
    "route": {
        "name": "The route name",
        "description": "A detailed description of the route",
        "created": "2012–12–19T08:46Z",
        "geometry": {
            "type": "text/x-ewkt",
            "data": ["file:...", "data:...", "http://"]
        }
    }
}

=== aptomar/apt-file-format/extras/tests/valid/asset-multi.json
{
    "date": "2012-12-19T08:46Z",
    "description": "Text description of the contents for presentation in a confirmation dialog.",
    "generator": { 
        "program": "SuperCool.app",
        "creator": "Aptomar AS"
    },
    "manifest_version": 1,
    "asset": {
        "layers": { 
            "layer-1": {
                "name": "Layer 1 Name",
                "geometry": {
                    "type": "text/x-shapefile",
                    "data": ["layers/layer1.shp", "layers/layer1.dbf", "layers/layer1.shx"]                
                },
                "style": {
                    "data": ["file:styles/layer1.xml", "data:...", "http://"],
                    "type": "text/x-sld"
                },
                "resources": {
                    "data": ["file:resource1.png", "file:resource2.png"]
                }
            },
            "layer-2": {
                "name": "Layer 2 Name",
                "geometry": {
                    "type": "text/x-shapefile",
                    "data": ["layers/layer1.shp", "layers/layer1.dbf", "layers/layer1.shx"]                
                },
                "style": {
                    "data": ["file:styles/layer1.xml", "data:...", "http://"],
                    "type": "text/x-sld"
                },
                "resources": {
                    "data": ["file:resource1.png", "file:resource2.png"]
                }
            }
         },
        "groups": { 
            "group-1": {
                "name": "Group 1 Name",
                "layers": ["layer-1"]
            },
            "group-2": {
                "name": "Group 2 Name",
                "layers": ["layer-1"]
            }
        }
    }
}
